server {
    listen 80;
    server_name 47.76.106.223;
    charset utf-8;
    
    # 核心：解除上传大小限制（设为100M，可根据需求调整为50M/200M）
    client_max_body_size 100M;  


    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://springboot-app:8089;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 100s;   # 连接超时时间
        proxy_read_timeout 100s;      # 读取超时时间
        proxy_send_timeout 100s;      # 发送超时时间
    }
}